# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20161023_0029'),
        ('wishlist_app', '0002_auto_20161024_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='join',
            field=models.ManyToManyField(related_name='User_in_Item', to='login_app.User'),
        ),
    ]
