# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 00:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20161023_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_hired',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
